name: CodeStyle
on: [push]
jobs:
  Python-Code-Styling:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pycodestyle
          pip install --upgrade pycodestyle
      - name: Analysing the code with pycodestyle (PEP8)
        run: |
          pycodestyle `find -type f -regex '.*.py' | tr '\n' ' '`
      - run: echo "This job's status is ${{ job.status }}."
